/// Paper Trading Tycoon — Environment Configuration
///
/// Provides type-safe access to environment-specific values injected at
/// build time via the `envied` package.
///
/// Three environments are supported:
///   - development  (.env.development)
///   - staging      (.env.staging)
///   - production   (.env.production)
///
/// The generated `env.dart` file is in .gitignore and must never be committed.
/// Each developer and CI runner creates their own from the .env.*.example templates.
///
/// Usage:
///   AppEnv.apiBaseUrl   → 'https://api.papertradingtycoon.com'
library;

/// Abstract interface for environment configuration.
/// The concrete implementation is generated by envied.
///
/// Run: `dart run build_runner build --delete-conflicting-outputs`
abstract interface class AppEnvConfig {
  /// Base URL for the Laravel REST API (no trailing slash).
  /// Example: 'https://api.papertradingtycoon.com'
  String get apiBaseUrl;

  /// Firebase project identifier for the current environment.
  String get firebaseProjectId;

  /// The environment name: 'development' | 'staging' | 'production'.
  String get environment;

  /// Whether this is a debug/development build.
  bool get isDebug;
}

/// Runtime environment accessor.
///
/// In main.dart, the concrete [AppEnvConfig] implementation is registered
/// via Riverpod so all services can read it without global state.
///
/// The envied-generated `Env` class implements [AppEnvConfig].
/// This abstraction allows easy switching between environments in tests.
abstract final class AppEnv {
  static AppEnvConfig? _instance;

  /// Registers the environment configuration singleton.
  /// Called once in main.dart before runApp().
  static void register(AppEnvConfig config) {
    _instance = config;
  }

  /// Returns the registered environment configuration.
  /// Throws a [StateError] if called before [register].
  static AppEnvConfig get instance {
    assert(
      _instance != null,
      'AppEnv.register() must be called before accessing AppEnv.instance.',
    );
    return _instance!;
  }

  /// Convenience accessors.
  static String get apiBaseUrl => instance.apiBaseUrl;
  static String get environment => instance.environment;
  static bool get isDebug => instance.isDebug;
  static bool get isProduction => instance.environment == 'production';
  static bool get isStaging => instance.environment == 'staging';
  static bool get isDevelopment => instance.environment == 'development';
}
