#!/usr/bin/env php
<?php

declare(strict_types=1);

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

// Register the Composer Autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
(require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Symfony\Component\Console\Input\ArgvInput);
